/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS roles (
	id UUID PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);